name: Build & Deploy Laravel App

on:
  push:
    branches:
      - '**'

jobs:
  test:
    name: Run Laravel Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Copy .env file
        run: cp .env.example .env

      - name: Install composer dependencies
        run: composer install --no-interaction --no-suggest

      - name: Set up Laravel Sail
        run: |
          ./vendor/bin/sail up -d
          echo "Attente du démarrage de PostgreSQL..."
          sleep 10
          ./vendor/bin/sail artisan key:generate
          ./vendor/bin/sail artisan migrate --force

      - name: Run test
        run: ./vendor/bin/sail artisan test

  docker:
    name: Build & Push Docker Image
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Laravel Docker image
        run: docker build -t llm-translate:latest -f docker/common/php-fpm/Dockerfile .

      - name: Vérifier les images Docker disponibles
        run: docker images

      - name: Tag and Push Docker Image
        run: |
          docker tag llm-translate:latest valerianc/llm-translate:latest
          docker push valerianc/llm-translate:latest


  deploy:
    name: Deploy to VPS
    runs-on: ubuntu-latest
    needs: docker
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Add SSH key and known hosts
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy to VPS
        run: |
          ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << 'EOF'
          set -e
          echo "Vérification de Docker et Docker Compose..."

          if ! command -v docker &> /dev/null; then
            echo "Installation de Docker..."
            curl -fsSL https://get.docker.com | sh
            sudo usermod -aG docker $USER
          fi

          if ! docker compose version &> /dev/null; then
            echo "Installation de Docker Compose..."
            sudo curl -L "https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
            sudo chmod +x /usr/local/bin/docker-compose
          fi

          echo "Mise à jour et redémarrage du conteneur Laravel..."
          cd /home/ubuntu/LLM_Translate/scripts
          docker pull valerianc/llm-translate:latest
          ./deploy-all.sh

          echo "Déploiement terminé. Liste des conteneurs actifs :"
          docker ps
          EOF
